on:
  release:
    types:
      - released
name: Demo Page
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Library and Docs
      run: make build_pages

    - name: Deploy
      if: success()
      # use the specific sha of 3rd party libraries for security reasons https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
      # Using tag v2.3.0
      uses: crazy-max/ghaction-github-pages@b8f8d291c97fe0edd9fb4ee73018163593418e8f
      with:
        target_branch: gh-pages
        build_dir: ./pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

